url: "http://ronam.us"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

title: "Adventures of Rohit and Onam"
description: "A collection of our adventures, experiences and thoughts"

minimal_mistakes_skin: "dirt" # You can change this to "dark", "air", "mint", "default" etc.

defaults:
  - scope:
      path: ""
      type: all
    values:
      layout: "single"
      author_profile: true
